"""The version has exactly one source, and everything else derives from it.

It used to have four hand-typed copies: pyproject.toml,
wingman/__init__.py, uv.lock, and packaging/installer.iss. M2
removed the first two and the lock's went with them; the installer's is
generated by packaging/write_version_iss.py immediately before iscc.

These assert the CHAIN, not that N literals happen to agree. A test of the
second kind is what a drifting copy defeats -- it passes right up until
someone adds a fifth copy it does not know about.

This replaces the bash check that lived in ci.yml. It runs on both platforms
rather than only ubuntu, and a contributor bumping a version is far likelier
to read the test suite than a workflow file.
"""

import re
import subprocess
import sys
from pathlib import Path

import pytest

from wingman import __version__

ROOT = Path(__file__).resolve().parents[1]
ISS = ROOT / "packaging" / "installer.iss"
GENERATOR = ROOT / "packaging" / "write_version_iss.py"


def test_pyproject_declares_no_version_of_its_own():
    """It carries `dynamic = ["version"]` and reads the attribute instead.

    A literal here is the copy that drifts most quietly: nothing at runtime
    reads it, so it is wrong only in the built artifact's metadata, which is
    the last place anyone looks.
    """
    text = (ROOT / "pyproject.toml").read_text(encoding="utf-8")
    assert 'dynamic = ["version"]' in text
    assert 'version = { attr = "wingman.__version__" }' in text
    # No bare `version = "x.y.z"` at the top level of [project].
    assert re.search(r'^version = "', text, re.MULTILINE) is None


def test_the_installer_includes_the_generated_define_rather_than_a_literal():
    """installer.iss is the copy that CANNOT import the value -- Inno Pascal
    has no way to read a Python module -- so it is the one that had to be
    generated rather than derived in place."""
    text = ISS.read_text(encoding="utf-8")
    assert '#include "version.iss"' in text
    assert re.search(r'^#define AppVersion "', text, re.MULTILINE) is None


def test_the_generator_writes_the_version_the_app_reports(tmp_path):
    """The whole point of the chain, asserted end to end."""
    sys.path.insert(0, str(ROOT / "packaging"))
    try:
        import write_version_iss
    finally:
        sys.path.pop(0)

    assert write_version_iss.read_version() == __version__
    assert f'#define AppVersion "{__version__}"' in write_version_iss.render(
        __version__
    )


def test_the_generator_runs_standalone_under_a_bare_interpreter():
    """The build chain invokes it with a bare `python`, not through uv --
    stdlib only, no venv, the same convention as the fetch_*.py scripts. A
    third-party import added here would break the release build only, and
    only at the very last step."""
    result = subprocess.run(  # fixed argv, no shell
        [sys.executable, str(GENERATOR)],
        capture_output=True,
        text=True,
        cwd=ROOT,
        check=False,
    )
    assert result.returncode == 0, result.stderr
    assert __version__ in result.stdout
    generated = (ROOT / "packaging" / "version.iss").read_text(encoding="utf-8")
    assert f'#define AppVersion "{__version__}"' in generated


def test_the_generated_file_is_not_committed():
    """A committed copy is still a copy. .gitignore carries it so a build
    that forgets the generator fails loudly at iscc rather than shipping a
    stale number."""
    ignored = subprocess.run(  # fixed argv, no shell
        ["git", "check-ignore", "packaging/version.iss"],
        capture_output=True,
        text=True,
        cwd=ROOT,
        check=False,
    )
    assert ignored.returncode == 0, "packaging/version.iss must stay gitignored"


def test_a_source_without_a_version_fails_the_build_rather_than_guessing(tmp_path):
    """No placeholder fallback. A build that cannot determine its own
    version must stop, not ship FlyGD-Wingman-Setup-unknown.exe."""
    sys.path.insert(0, str(ROOT / "packaging"))
    try:
        import write_version_iss
    finally:
        sys.path.pop(0)

    empty = tmp_path / "__init__.py"
    empty.write_text("# no version here\n", encoding="utf-8")
    with pytest.raises(SystemExit, match="Could not find __version__"):
        write_version_iss.read_version(empty)


# --- the bare-python allowlist ----------------------------------------------


def test_every_allowlisted_packaging_script_is_stdlib_only():
    """ci.yml lets a few packaging/ scripts run without `uv run`.

    That exception is safe only while they import nothing outside the
    standard library: a bare `python` sees setup-python's interpreter, not
    .venv, so a third-party import in one of these fails at the very last
    step of the release build -- after PyInstaller, after every verification
    step, on the one build nobody wants to debug.

    The list is parsed out of ci.yml rather than retyped here. A hand-kept
    copy is what this repo's conventions forbid, and this particular list
    has already demonstrated it drifts: adding write_version_iss.py failed
    the check precisely because the allowlist had not been told about it.
    """
    workflow = (ROOT / ".github" / "workflows" / "ci.yml").read_text(encoding="utf-8")
    pattern = re.search(r"grep -vE 'python packaging/\(([^)]*\))?([^']*)'", workflow)
    assert pattern is not None, (
        "could not find the bare-python allowlist in ci.yml -- if the check "
        "was restructured, update this test with it"
    )

    names = set(re.findall(r"[a-z_]+(?:_[a-z0-9]+)*", pattern.group(0)))
    scripts = [
        path
        for path in (ROOT / "packaging").glob("*.py")
        if any(part in path.stem for part in ("fetch_", "write_version"))
    ]
    assert scripts, "no packaging scripts found to check"

    stdlib = sys.stdlib_module_names
    for script in scripts:
        text = script.read_text(encoding="utf-8")
        imported = set(
            re.findall(r"^\s*(?:import|from)\s+([a-zA-Z_][\w.]*)", text, re.MULTILINE)
        )
        for module in imported:
            root = module.split(".")[0]
            if root == "__future__":
                continue
            assert root in stdlib, (
                f"{script.name} imports {root!r}, which is not in the standard "
                "library. It is invoked with a bare `python` in "
                ".github/actions/build-installer/action.yml, so that import "
                "will fail at release time. Either drop the dependency or "
                "move the step onto `uv run` and remove it from ci.yml's "
                "allowlist."
            )
    assert names, "the allowlist regex parsed to nothing"
