"""Supervise the EVE bookmark hotkey engine.

AutoHotkey is confined to this module: nothing in its public interface
names it. That is deliberate -- the naming logic may later be reimplemented
in Python, and this boundary is what makes that a swap rather than a
rewrite of the integration.

Windows-only at runtime, importable and testable everywhere: the process is
reached only through an injected spawner.

The spawn/job/pid/orphan quartet lives in procguard (shared with the
stream-mirror supervisor, #317); this module keeps the engine-specific
half -- the INI channel, the status document and its bounds, the prime
record.
"""

import json
import logging
import re
import subprocess
import sys  # noqa: F401 -- tests patch hotkeys.sys.platform
import time
import uuid
from dataclasses import dataclass, field
from pathlib import Path

from . import atomicio, bookmarks, paths, procguard, procid

logger = logging.getLogger(__name__)

# The engine republishes every 2s (111unified.ahk:77). Three missed ticks
# is a deliberate margin: one missed write on a busy machine is normal, a
# sustained gap means it is alive but not working.
STALE_AFTER_S = 6.0

# The engine's document is a handful of short strings. A file larger than
# this is not something the engine wrote; refuse it whole rather than parse
# it, so the prime bound is enforced before any JSON work happens.
_MAX_STATUS_CHARS = 4096

# CREATE_NO_WINDOW doesn't exist off Windows, and the tests inject a fake
# spawner -- same shape as stitch.py:27 and library.py:19. Re-exported from
# procguard (the implementation); tests patch THIS name, and HotkeyEngine
# reads it at construction so the patch is what the spawn actually uses.
_NO_WINDOW_KWARGS = procguard.NO_WINDOW_KWARGS

_MISSING = (
    "The bookmark engine is missing from this installation. "
    "Reinstall FlyGD Wingman to restore it."
)

# Names this module's tests (and the reclamation path) have always used;
# the implementations are procguard's now.
_default_job = procguard.default_job

_ENGINE_IMAGE_NAME = "autohotkeyu64.exe"
_KernelJob = procguard.KernelJob


@dataclass
class EngineStatus:
    """What the UI renders. `state` is authoritative; the values are only
    populated when state == "running"."""

    state: str = "off"
    sig: str | None = None
    root: str | None = None
    next_num: str | None = None
    next_alpha: str | None = None
    failed_binds: list = field(default_factory=list)
    last_error: str | None = None
    prime: "PrimeRecord | None" = None


@dataclass(frozen=True)
class PrimeRecord:
    """A pre-jump prime captured by the engine's Set Root (#295).

    The engine fills this only when Set Root fired on a single selected
    bookmark; every other Set Root path leaves it absent. `flags` holds the
    finisher-tag vocabulary the engine writes into bookmark names: `e`
    stacks, `/` and `c` are mutually exclusive, `f` is independent. `event`
    is the engine's idempotency key for the staged prime downstream.
    """

    jcode: str
    flags: tuple
    event: str
    captured: float


def _text(value) -> str | None:
    """Coerce a status value for display, or None if it is empty.

    These reach a label; a dict or list from a corrupt file would otherwise
    be rendered as its repr. bool is excluded deliberately -- str(True) is
    "True", which would render as a root system named True.
    """
    if value is None or isinstance(value, (dict, list, bool)):
        return None
    text = str(value).strip()
    return text or None


# A prime record larger than this is not a prime, it is an attack, so the
# document it arrived in is not trustworthy (mirrors the failed_binds rule).
# A real record is a J-code (<=7 chars), up to three one-char flags, a hex
# event id and an epoch float -- bytes, not kilobytes.
PRIME_MAX_JSON_CHARS = 256
PRIME_MAX_FLAGS = 3

# PrimeEvent is a UUID hex generated by the engine; caps the id length.
PRIME_MAX_EVENT_CHARS = 64

_JCODE_RE = re.compile(r"^[A-Z0-9]{1,7}$")
_PRIME_FLAG_RE = re.compile(r"^[e/cf]$")
_PRIME_EVENT_RE = re.compile(r"^[0-9a-f]{8,64}$")


def _prime_from_raw(raw):
    """Parse the engine's `prime` field, or None.

    Strictly typed: None (absent -- the common case, every Set Root path
    except a single selected bookmark) is the zero value; anything that is
    not a well-formed record is rejected whole rather than repaired, so a
    corrupt field can never half-populate a record that downstream code
    stages. Rejection is local: the surrounding status document's other
    fields are unaffected.
    """
    if raw is None:
        return None
    if not isinstance(raw, dict):
        logger.warning("Engine status has a malformed prime field.")
        return None
    jcode = raw.get("jcode")
    event = raw.get("event")
    captured = raw.get("captured")
    flags = raw.get("flags")
    if not isinstance(jcode, str) or not _JCODE_RE.match(jcode):
        logger.warning("Engine status prime has a malformed jcode.")
        return None
    if not isinstance(event, str) or not _PRIME_EVENT_RE.match(event):
        logger.warning("Engine status prime has a malformed event id.")
        return None
    if isinstance(captured, bool) or not isinstance(captured, (int, float)):
        logger.warning("Engine status prime has a malformed capture time.")
        return None
    if not isinstance(flags, list) or len(flags) > PRIME_MAX_FLAGS:
        logger.warning("Engine status prime has a malformed flag list.")
        return None
    clean_flags = []
    for flag in flags:
        if not isinstance(flag, str) or not _PRIME_FLAG_RE.match(flag):
            logger.warning("Engine status prime has a malformed flag.")
            return None
        clean_flags.append(flag)
    # Engine-side rules: e stacks; / and c are mutually exclusive; f is
    # independent. A record violating them was not produced by today's
    # engine, so it is rejected rather than interpreted.
    if "/" in clean_flags and "c" in clean_flags:
        logger.warning("Engine status prime has conflicting / and c flags.")
        return None
    if len(set(clean_flags)) != len(clean_flags):
        logger.warning("Engine status prime has a duplicate flag.")
        return None
    return PrimeRecord(
        jcode=jcode,
        flags=tuple(clean_flags),
        event=event,
        captured=float(captured),
    )


class HotkeyEngine:
    """Own the engine process and the files it reads.

    Process guardianship is procguard's (job object, pid record, orphan
    recovery, stop escalation); the engine-specific half is apply()'s INI
    channel and status()'s liveness-driven document read. A record left
    behind by a crashed session is deliberately not cleaned up here: that
    decision belongs to recovery, which verifies the process image and the
    run token before terminating anything.
    """

    def __init__(
        self,
        exe,
        script,
        state_dir,
        *,
        spawner=subprocess.Popen,
        token_factory=lambda: uuid.uuid4().hex,
        job_factory=_default_job,
    ):
        # Engine test doubles patch module globals (hotkeys.procid,
        # hotkeys._NO_WINDOW_KWARGS) before construction; reading them
        # NOW is what makes those patches reach the spawn.
        self._guard = procguard.ProcGuard(
            exe,
            state_dir,
            pid_name=paths.engine_pid_file().name,
            image_name="AutoHotkeyU64.exe",
            spawner=spawner,
            token_factory=token_factory,
            job_factory=job_factory,
            procid_module=procid,
            no_window_kwargs=_NO_WINDOW_KWARGS,
        )
        self._state_dir = Path(state_dir)
        self._script = Path(script) if script else None
        self.last_error = self._guard.last_error

    # -- config ------------------------------------------------------
    def apply(self, section: dict) -> None:
        """Regenerate the INI the engine reads.

        The engine picks this up on its own 10s timer, so there is no need
        to restart it and lose in-flight state (root system, used slots).
        """
        atomicio.write_atomic(self._ini_path(), bookmarks.generate_ini(section))

    # -- lifecycle ---------------------------------------------------
    def start(self) -> bool:
        script = self._script
        ok = self._guard.launch(
            lambda token: [str(self._guard.exe_path()), str(script), "/token", token],
            required_paths=(script,),
            missing_message=_MISSING,
            failure_message="The bookmark engine could not start",
        )
        self.last_error = self._guard.last_error
        return ok

    def stop(self, timeout: float = 5.0) -> None:
        """Stop the engine and clear its PID record (procguard)."""
        self._guard.stop(timeout=timeout)

    def is_running(self) -> bool:
        return self._guard.is_running()

    def recover_orphan(self) -> bool:
        """Terminate an engine left behind by a crashed Wingman
        (procguard; identity = image name AND run token)."""
        return self._guard.recover_orphan()

    def status(self, enabled: bool, now: float | None = None) -> EngineStatus:
        """Report engine state, driven by liveness rather than file contents.

        The status file outlives the process that wrote it. Reading values
        from it without first establishing that the engine is alive is how
        a dead root system gets displayed as the current one.
        """
        if not enabled:
            return EngineStatus(state="off")
        if not self.is_running():
            return EngineStatus(state="stopped", last_error=self.last_error)

        now = time.time() if now is None else now
        try:
            text = self._status_path().read_text(encoding="utf-8")
            # A bounded engine document cannot carry a bounded prime. Check
            # the size before parsing: json.loads on attacker-sized input is
            # the failure mode the bound exists to prevent.
            if len(text) > _MAX_STATUS_CHARS:
                logger.warning("Engine status file is oversized; ignoring it.")
                return EngineStatus(state="stale")
            raw = json.loads(text)
            written = float(raw["written"])
        except (OSError, ValueError, KeyError, TypeError):
            return EngineStatus(state="stale")
        if now - written > STALE_AFTER_S:
            return EngineStatus(state="stale")

        failed = raw.get("failed_binds")
        if not isinstance(failed, list):
            # A wrong-typed field means the document is not trustworthy, and
            # there is no reason to believe `root` while disbelieving this.
            # Reporting [] would be worse than reporting nothing: it says
            # "every hotkey registered fine", which is exactly what we do
            # not know.
            logger.warning("Engine status has a malformed failed_binds.")
            return EngineStatus(state="stale")

        return EngineStatus(
            state="running",
            sig=_text(raw.get("sig")),
            root=_text(raw.get("root")),
            next_num=_text(raw.get("next_num")),
            next_alpha=_text(raw.get("next_alpha")),
            failed_binds=[str(b) for b in failed],
            prime=_prime_from_raw(raw.get("prime")),
        )

    # -- paths -------------------------------------------------------
    def _ini_path(self) -> Path:
        return self._state_dir / paths.engine_ini_file().name

    def _pid_path(self) -> Path:
        return self._state_dir / paths.engine_pid_file().name

    def _status_path(self) -> Path:
        return self._state_dir / paths.engine_status_file().name

    def _clear_pid_record(self) -> None:
        try:
            self._pid_path().unlink()
        except OSError as exc:
            # Non-fatal on purpose: every caller is a path that must reach
            # its own outcome whether or not the record went away, and the
            # next recover_orphan clears it anyway once the pid is dead. It
            # is logged rather than passed over because a record that
            # repeatedly cannot be removed means something holds it -- an
            # AV scanner, a permissions change -- and that is invisible
            # from the outside otherwise.
            logger.warning("Could not remove the engine PID record: %s", exc)
