"""Emit the state-v1/v2/v3 approval-URL text predicate using CPython Unicode 14.

Run with Python 3.11, then format the output with Ruff. This is deliberately
independent of the combat-v2 profile: future runtimes must not expand which
historical documents can be admitted as valid evidence.
"""

import unicodedata

if unicodedata.unidata_version != "14.0.0":
    raise SystemExit("This generator requires Unicode 14.0.0 (Python 3.11).")

boundaries = []
previous = False
for codepoint in range(0x110000):
    char = chr(codepoint)
    allowed = not unicodedata.category(char).startswith("C") and not char.isspace()
    if allowed != previous:
        boundaries.append(codepoint)
        previous = allowed
if previous:
    boundaries.append(0x110000)

print('''"""Frozen legacy approval-URL text, not the combat-v2 name profile.

Generated by scripts/generate_legacy_text.py with CPython Unicode 14.0.0.
Boundary pairs delimit non-C, non-whitespace ranges, with exclusive ends.
Do not regenerate with a newer Unicode database: these are historical rules.
"""

from bisect import bisect_right

_BOUNDARIES = (''')
for index in range(0, len(boundaries), 8):
    print(
        "    "
        + ", ".join(f"0x{value:X}" for value in boundaries[index : index + 8])
        + ","
    )
print(''')


def valid_legacy_url_text(value: str) -> bool:
    """Reject controls, unassigned scalars and whitespace as Unicode 14 did."""
    return all(bisect_right(_BOUNDARIES, ord(char)) % 2 for char in value)
''')
