"""Filesystem locations for application state and bundled resources.

State never lives next to the executable: the installer targets Program
Files, which is read-only for non-admin users.
"""
import os
import shutil
import sys
from pathlib import Path

APP_NAME = "OBSYouTubeUploader"


def state_dir() -> Path:
    """Per-user writable directory for settings, token, logs, and temp files."""
    base = os.environ.get("LOCALAPPDATA")
    if base:
        return Path(base) / APP_NAME
    # Non-Windows fallback so tests and development work off-platform.
    return Path.home() / ".local" / "share" / APP_NAME


def settings_file() -> Path:
    return state_dir() / "settings.json"


def token_file() -> Path:
    return state_dir() / "token.json"


def seen_file() -> Path:
    return state_dir() / "seen.json"


def durations_file() -> Path:
    """Cache of ffprobe durations. Deleting it costs a one-off re-probe."""
    return state_dir() / "durations.json"


def log_dir() -> Path:
    return state_dir() / "logs"


def tmp_dir() -> Path:
    return state_dir() / "tmp"


def bundle_dir() -> Path:
    """Directory holding bundled binaries.

    PyInstaller unpacks to sys._MEIPASS; in a source checkout it is the
    repository root.
    """
    meipass = getattr(sys, "_MEIPASS", None)
    if meipass:
        return Path(meipass)
    return Path(__file__).resolve().parent.parent


def resolve_binary(name: str) -> str | None:
    """Find a bundled binary, falling back to PATH.

    In a frozen build, `bundle_dir()` is `sys._MEIPASS` and the bundled
    binary lives at its `bin/` subfolder — that path is verified correct
    and left untouched. In a source checkout, `bundle_dir()` is the repo
    root, but `packaging/fetch_ffmpeg.py` writes into `packaging/bin`, not
    `<repo>/bin`. Without this extra lookup, running from source never
    finds the fetched ffmpeg and silently falls back to PATH.
    """
    exe = f"{name}.exe"
    candidate = bundle_dir() / "bin" / exe
    if candidate.exists():
        return str(candidate)
    candidate = bundle_dir() / exe
    if candidate.exists():
        return str(candidate)
    if not hasattr(sys, "_MEIPASS"):
        candidate = bundle_dir() / "packaging" / "bin" / exe
        if candidate.exists():
            return str(candidate)
    return shutil.which(name)


def icon_file() -> Path | None:
    """Locate the bundled app icon, or None if it isn't present.

    Mirrors app.resolve_binary()'s two-case handling of bundle_dir():
    frozen builds collect the icon at the bundle root via uploader.spec's
    `datas` entry, so `bundle_dir() / "app.ico"` is correct there. A source
    checkout has no such collection step, so bundle_dir() (the repo root)
    is wrong; the real file lives under the package's own assets/ folder.
    Returning None rather than raising lets callers treat a missing icon as
    optional, the same policy resolve_binary() and configure_logging() use.
    """
    frozen_candidate = bundle_dir() / "app.ico"
    if frozen_candidate.exists():
        return frozen_candidate
    source_candidate = Path(__file__).resolve().parent / "assets" / "app.ico"
    if source_candidate.exists():
        return source_candidate
    return None


def engine_ini_file() -> Path:
    """Config the engine reads. Generated by Wingman, never hand-edited.

    The name matches the standalone script's IniFile (111unified.ahk:71),
    which is relative -- so spawning the engine with cwd=state_dir() is what
    makes it resolve here with no edit to the script.
    """
    return state_dir() / "eve_bookmark_helper.ini"


def engine_status_file() -> Path:
    """Runtime state the engine publishes. Wingman never writes this."""
    return state_dir() / "eve_status.json"


def engine_command_file() -> Path:
    """Operations Wingman publishes. The engine never writes this.

    INI rather than JSON, unlike the status file, because the direction of
    travel decides the format: AHK reads INI natively via IniRead and has no
    JSON parser, while it only ever *writes* the status file, which string
    concatenation handles fine. Each side does its easy direction.
    """
    return state_dir() / "eve_command.ini"


def engine_pid_file() -> Path:
    """PID plus run token of the last spawned engine, for orphan recovery."""
    return state_dir() / "eve_engine.pid"


def _package_dir() -> Path:
    return Path(__file__).resolve().parent


def engine_script() -> Path | None:
    """Locate the vendored .ahk, or None if it is not present.

    Mirrors icon_file()'s two-case handling of bundle_dir(): a frozen build
    collects the script via uploader.spec's datas entry, a source checkout
    has it inside the package.
    """
    frozen = bundle_dir() / "engine" / "eve_bookmarks.ahk"
    if frozen.exists():
        return frozen
    source = _package_dir() / "engine" / "eve_bookmarks.ahk"
    if source.exists():
        return source
    return None


def engine_exe() -> str | None:
    """Locate the bundled AutoHotkey interpreter. Bundled only.

    Deliberately NOT resolve_binary(): its shutil.which() fallback is
    correct for ffmpeg and dangerous here. AutoHotkey v2 is a different,
    incompatible language, and a v2 interpreter on PATH handed our v1
    script fails with parse errors that read like a bug in the script.
    Better to report a missing engine and have the user reinstall.
    """
    name = "AutoHotkeyU64.exe"
    candidate = bundle_dir() / "bin" / name
    if candidate.exists():
        return str(candidate)
    if not hasattr(sys, "_MEIPASS"):
        candidate = bundle_dir() / "packaging" / "bin" / name
        if candidate.exists():
            return str(candidate)
    return None


def ensure_dirs() -> None:
    for d in (state_dir(), log_dir(), tmp_dir()):
        d.mkdir(parents=True, exist_ok=True)
