"""Write packaging/version.iss from obs_youtube_uploader.__version__.

The version used to be typed by hand in four places: pyproject.toml,
obs_youtube_uploader/__init__.py, uv.lock, and packaging/installer.iss. M2
removed the first two (pyproject derives through setuptools' dynamic
metadata, and the lock stopped recording one as a consequence). This removes
the last, which is the one that could not simply import the value: Inno
Pascal has no way to read a Python module.

DESIGN.md's rule is "Derive it, or assert it in a test." Both were on the
table and deriving wins -- an assertion tells you after the fact that two
copies disagree, and there is then still a human who has to go and fix one.

Read textually, not imported. This runs from a bare `python` in the build
chain (the same convention as fetch_ffmpeg.py and its siblings -- stdlib
only, no venv), and importing the package would drag in whatever
__init__.py grows later for a value that is one literal assignment.

Stdlib only, and no third-party imports, for that same reason.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "obs_youtube_uploader" / "__init__.py"
TARGET = Path(__file__).resolve().parent / "version.iss"

_PATTERN = re.compile(r'^__version__\s*=\s*"([^"]+)"', re.MULTILINE)


def read_version(source: Path = SOURCE) -> str:
    """The declared version, or raise with a message naming the file.

    Raises rather than falling back to a placeholder. A build that cannot
    determine its own version must fail here, loudly, and not ship an
    installer called FlyGD-Wingman-Setup-unknown.exe.
    """
    text = source.read_text(encoding="utf-8")
    match = _PATTERN.search(text)
    if match is None:
        raise SystemExit(
            f"Could not find __version__ in {source}. "
            "packaging/installer.iss derives its AppVersion from it and "
            "the installer cannot be built without one."
        )
    return match.group(1)


def render(version: str) -> str:
    return (
        "; GENERATED by packaging/write_version_iss.py -- do not edit, and do\n"
        "; not commit. The single source is obs_youtube_uploader/__init__.py.\n"
        f'#define AppVersion "{version}"\n'
    )


def main() -> int:
    version = read_version()
    TARGET.write_text(render(version), encoding="utf-8")
    print(f"{TARGET.relative_to(ROOT)}: AppVersion {version}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
